### ISSUE TITLE
Share URL option not working

### ISSUE THREAD

**Issue by andyclegg** [mayankmkh/linear-app-plugin#167]
I saw that in #21, a share URL option was added. However, I am unable to see this option on Linear task servers (though I can see it on other task server types, like Jira). Has there been a regression/API change? Thanks.

I am using Linear Tasks v1.1.0 and PyCharm 2023.1 (Professional Edition), Build #PY-231.8109.197, built on March 29, 2023.

**Comment by mayankmkh** [comment]
Thanks for reporting the issue! I rechecked the documentation and found that the share URL is not meant to share the configuration across projects, in fact it seems like it's not possible at all. Ref: https://youtrack.jetbrains.com/issue/IDEA-137068. 

From [IntelliJ docs](https://www.jetbrains.com/help/idea/managing-tasks-and-context.html#connect-to-tracker)
> Select the Share URL option to allow access to the server for other members of your team. When this option is enabled, a server URL and its type are saved to the .idea/misc.xml file, which can be shared between development team members through version control.

I found another interesting thing though that might be helpful. On Mac (need to check on other platforms), IntelliJ now shows all configured servers in the add new server list, so it's just one click configuration. Hope that helps!
