### ISSUE TITLE
Cannot connect to api.linear.app/graphql

### ISSUE THREAD

**Issue by blascokoa** [mayankmkh/linear-app-plugin#186]
Cannot connect to linear, it reports cannot connect and give the option to setup the server, tried to setup a new apikey and did the connection test, it works, but at the time of fetch the tasks it still raises the error cannot connect to api.

![image](https://github.com/mayankmkh/linear-app-plugin/assets/37955180/fa63766e-46ec-4d05-ab00-26a0233df6b3)

![image](https://github.com/mayankmkh/linear-app-plugin/assets/37955180/dceb273e-04c0-40f6-bb25-b006183576d3)

**Comment by pymen** [comment]
@mayankmkh does it make sense to create new release based on current state of "master" branch?

**Comment by banagale** [comment]
I have this same issue.

I can connect in the server setup dialog but can't actually open or switch tasks. Not sure how search tasks is pulled up.

When I try to go Tools -> Tasks & Contexts -> Open Tasks...

Error is: `Cannot connect to https://api.linear.app/graphql` with a highlighted Configure Server...

When I change the three letter team ID to something random, the server setup connection test fails. 

So I think I have auth credentials correct.

@pymen does main have a working version of this plugin?  Anyone have a workaround?

**Comment by pymen** [comment]
@banagale 

When I try to go Tools -> Tasks & Contexts -> Open Tasks..

List with tasks does not work, but you can search ticket by exact match usign <TEAMID>-<TASKID> pattern, like BC-172

**Comment by mayankmkh** [comment]
Thanks for your patience! A new version is available that fixes the issue. Please note that due to a breaking change, you'll need to reconfigure the task server. Feel free to reopen the issue if the problem persists. Have a great day!

**Comment by KaKi87** [comment]
Hi @mayankmkh why did you stop maintaining this ?
