### ISSUE TITLE
Enable Share URL option

### ISSUE THREAD

**Issue by umbertix** [mayankmkh/linear-app-plugin#21]
Would be nice to be able to share the linear configuration across different project. Currently we need to add for every project.

**Comment by mayankmkh** [comment]
Thanks for raising the issue. I'm looking for some help and would love to have some contributions. Let me know if you are interested to implement this feature.

**Comment by umbertix** [comment]
Would love to help, I don't have a lot of time nor experience with this language but will try look into it. If you have any pointers would be awesome, otherwise will try to look into documentation before the end of the month.

**Comment by mayankmkh** [comment]
No worries! I also didn't know anything about plugin development but Jakub Chrzanowski and Mikhail Golubev from Jetbrains helped me get started. They pointed me to some great references. You can check them in the thread on Youtrack https://youtrack.jetbrains.com/issue/IDEA-265362.

**Comment by mayankmkh** [comment]
@umbertix I think this is fixed in v1.0.0-alpha03. Can you please install the latest version of the plugin and verify the fix, please?

**Comment by umbertix** [comment]
It is working, that's fantastic. Thanks a lot :), will close the issue
