### ISSUE TITLE
Update Linear task status

### ISSUE THREAD

**Issue by umbertix** [mayankmkh/linear-app-plugin#22]
As an improvement would be nice to be able to update the status of the task when the context menu is displayed.

**Comment by mayankmkh** [comment]
I'm working on this now and should soon be complete. I will update here when it's done. Thanks

**Comment by umbertix** [comment]
Fantastic, I've never coded on Kotlin or Java, so still getting somewhat aquainted with it. But would be great to see the branch, as per pure curiosity :)

**Comment by mayankmkh** [comment]
@umbertix I've implemented this feature. Please have a look at the code in PR #23.
