### ISSUE TITLE
Configuration not persisted

### ISSUE THREAD

**Issue by umbertix** [mayankmkh/linear-app-plugin#30]
Every time that I restart WebStorm, my task server dissapears. It does not persist the configuration apparently.

Steps to reproduce: 
- Open Webstorm
- Add a task server
- Close Webstorm
- Open webstorm and validate that the task server is no longer available on the list

**Comment by mayankmkh** [comment]
Thanks for raising the issue. I've fixed it in [Configuration not persisted](https://github.com/mayankmkh/linear-app-plugin/commit/e9f93652da8bea454adf9a5f61ec82b2542b3bc1). Will release a new version in a couple of days. Feel free to reopen this if the issue still persists.
